---

- name: Populate service facts
  service_facts:

- name: Gather package facts
  package_facts:
    manager: auto

- name: Add yum repo for podman (Amazon Linux)
  get_url:
    url: 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/devel:kubic:libcontainers:stable.repo'
    dest: '/etc/yum.repos.d/devel:kubic:libcontainers:stable.repo'
  when:
    ansible_distribution == 'Amazon'
    
- name: Install Copr (Amazon)
  yum:
    name: yum-plugin-copr
    state: present
  when:
    (ansible_distribution == 'Amazon')

- name: Enable Copr (Amazon)
  command: yum -y copr enable lsm5/container-selinux
  args:
    creates: /etc/yum.repos.d/_copr_lsm5-container-selinux.repo
  when:
    (ansible_distribution == 'Amazon')

- name: Install podman (RedHat/CentOS/Fedora)
  yum:
    name: podman
    state: present
    enablerepo:
      - rhui-rhel-7-server-rhui-optional-rpms
      - rhui-rhel-7-server-rhui-extras-rpms
  when: 
    (ansible_distribution == 'RedHat') or
    (ansible_distribution == 'Fedora') or
    (ansible_distribution == 'Amazon') or
    (ansible_distribution == 'CentOS') 

# TODO This requires a reboot
- name: Disable metacopy (Amazon)
  lineinfile:
    path: /etc/containers/storage.conf
    regexp: '^mountopt = "nodev,metacopy=on"'
    line: 'mountopt = "nodev"'

